import { useState, type FormEvent } from 'react';
export async function accountRequest(path:string, body:unknown) {
  const res=await fetch('/api/auth/'+path,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(body)});
  const data=await res.json(); if(!res.ok) throw new Error(data.error ?? 'Request failed.'); return data;
}
export function AccountForms({onDone}:{onDone:()=>void}) {
  const [mode,setMode]=useState<'register'|'recover'>('register');
  const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [businessName,setBusinessName]=useState('');const [code,setCode]=useState('');
  const [result,setResult]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  async function submit(e:FormEvent) {e.preventDefault();setBusy(true);setError('');try{const r=await accountRequest(mode,{email,password,businessName,recoveryCode:code});setResult(r.recoveryCode);setPassword('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const input='mt-1 w-full rounded border p-3';
  return <section className="mt-8 border-t pt-6"><div className="flex gap-4"><button type="button" onClick={()=>{setMode('register');setResult('');setError('');}}>Create account</button><button type="button" onClick={()=>{setMode('recover');setResult('');setError('');}}>Recover account</button></div><h2 className="mt-4 text-lg font-semibold">{mode==='register'?'Create your business account':'Reset using your recovery code'}</h2>{result?<div role="status" className="mt-4 rounded bg-amber-50 p-4"><p>Save this recovery code privately. It replaces any previous code and is shown only here. Use it to reset your password without email.</p><code className="block break-all py-3 select-all">{result}</code><button onClick={()=>{setResult('');onDone();}}>Saved — return to sign in</button></div>:<form onSubmit={submit} className="mt-4 space-y-3"><label className="block">Account email<input className={input} type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label>{mode==='register'?<label className="block">Business name<input className={input} required maxLength={100} value={businessName} onChange={e=>setBusinessName(e.target.value)}/></label>:<label className="block">Recovery code<input className={input} required value={code} onChange={e=>setCode(e.target.value)}/></label>}<label className="block">New password (at least 12 characters)<input className={input} type="password" required minLength={12} maxLength={200} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p role="alert" className="text-red-700">{error}</p>}<button disabled={busy} className="rounded bg-indigo-600 px-4 py-3 text-white">{busy?'Saving…':mode==='register'?'Create account':'Reset password'}</button></form>}</section>;
}
export function PasswordSettings() {
  const [currentPassword,setCurrent]=useState('');const [password,setPassword]=useState('');const [code,setCode]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await accountRequest('password',{currentPassword,password});setCode(r.recoveryCode);setCurrent('');setPassword('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <section className="rounded border bg-white p-6"><h2 className="text-lg font-semibold">Account security</h2>{code?<div role="status"><p>Password changed. Save your new recovery code, then sign in again. All old sessions and recovery codes have been revoked.</p><code className="block break-all py-3 select-all">{code}</code><a href="/owner/sign-in">Return to sign in</a></div>:<form onSubmit={submit} className="mt-4 space-y-3"><label className="block">Current password<input type="password" className="block w-full rounded border p-3" required autoComplete="current-password" value={currentPassword} onChange={e=>setCurrent(e.target.value)}/></label><label className="block">New password<input type="password" className="block w-full rounded border p-3" required minLength={12} maxLength={200} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p role="alert" className="text-red-700">{error}</p>}<button disabled={busy} className="rounded bg-indigo-600 px-4 py-3 text-white">{busy?'Saving…':'Change password'}</button></form>}</section>;
}
