import type { Amplify } from 'aws-amplify';

/**
 * amplify_outputs.json is generated by `npx ampx sandbox` or by the Amplify
 * Hosting build (`ampx pipeline-deploy`). It is git-ignored, so it may be
 * missing; the glob then matches nothing instead of failing the build.
 */
type AmplifyConfig = Parameters<typeof Amplify.configure>[0];

const found = import.meta.glob<AmplifyConfig & { custom?: { publicChatUrl?: string } }>('../../../amplify_outputs.json', {
  eager: true,
  import: 'default',
});

export const amplifyOutputs = Object.values(found)[0];

export const publicChatUrl: string | undefined = import.meta.env.VITE_PUBLIC_CHAT_URL || amplifyOutputs?.custom?.publicChatUrl;
